### ISSUE TITLE
folder missing ?

### ISSUE THREAD

**Issue by montanier** [ZheLI0319/PepperHHBdx#1]
Hello,

I have the following error at the line 11:
from democall import DemoCall                                                                        
ImportError: No module named democall

Maybe the folder "DemoCall" is missing ?

Jean-Marc

**Comment by ZheLI0319** [comment]
hello,
I didn't work on this part. but i can ask.
Zhe

**Comment by julio-matarranz** [comment]
Hi,
The module has been deleted in commit [b84d0b0 ](https://github.com/ZheLI0319/PepperHHBdx/commit/b84d0b0d112808b7ceace5a57a05ecb48f99994c) and the import has been removed in commit [09c9085](https://github.com/ZheLI0319/PepperHHBdx/commit/09c9085232161a5c4815a9757fa99dcc771edf20).
Julio
